# Generated by Django 5.1.5 on 2025-04-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_friends'),
        ('collection', '0010_remove_pokemon_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_trade', to='accounts.profile')),
                ('receiver_pokemon', models.ManyToManyField(blank=True, related_name='receiver_pokemon_trade', to='collection.pokemon')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_trade', to='accounts.profile')),
                ('sender_pokemon', models.ManyToManyField(blank=True, related_name='sender_pokemon_trade', to='collection.pokemon')),
            ],
        ),
    ]
