# Generated by Django 5.1.5 on 2025-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('countered', 'Countered'), ('canceled', 'Canceled')], default='pending', max_length=100),
        ),
    ]
