# Generated by Django 5.1.5 on 2025-04-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
    ]
