# Generated by Django 5.1.5 on 2025-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
