# Generated by Django 5.1.5 on 2025-04-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_friends'),
        ('collection', '0004_alter_pokemon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
