# Generated by Django 5.1.5 on 2025-04-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_pokemon_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='poke_name',
            new_name='pokemon',
        ),
    ]
