# Generated by Django 5.2 on 2025-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_rename_poke_name_pokemon_pokemon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'Pokemon'},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
