# Generated by Django 5.1.5 on 2025-04-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default='rand', max_length=100),
            preserve_default=False,
        ),
    ]
