# Generated by Django 5.1.5 on 2025-04-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_pokemon_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
    ]
