# Generated by Django 5.2 on 2025-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_alter_pokemon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
