# Generated by Django 5.1.5 on 2025-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_currency'),
        ('collection', '0011_alter_pokemon_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('listed', 'Listed for Sale')], default='available', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.pokemon')),
            ],
        ),
    ]
