# Generated by Django 5.1.5 on 2025-04-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_alter_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
