# Generated by Django 5.1.5 on 2025-04-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_pokemon_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='is_custom',
        ),
    ]
