# Generated by Django 5.1.5 on 2025-04-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_remove_pokemon_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
