# Generated by Django 5.2 on 2025-04-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_collectedpokemon'),
        ('collection', '0015_pokemon_favorite'),
    ]

    operations = [
    ]
