# Generated by Django 5.1.5 on 2025-04-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_friends'),
        ('collection', '0010_remove_pokemon_types'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='accounts.profile')),
                ('pokemon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collection.pokemon')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='marketPlacePokemon',
        ),
    ]
