# Generated by Django 5.1.5 on 2025-04-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_delete_marketplacepokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
