# Generated by Django 5.2 on 2025-04-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_listing_buyer_alter_listing_date_posted_and_more'),
        ('marketplace', '0004_alter_listing_buyer_alter_listing_seller'),
    ]

    operations = [
    ]
