# Generated by Django 5.0 on 2025-04-28 15:17

import django.db.models.deletion
from django.db import migrations, models
from accounts.models import Profile


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_friendrequest_options_alter_profile_currency'),
        ('marketplace', '0005_merge_20250427_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='accounts.Profile'),
        ),
    ]
