# Generated by Django 5.0 on 2025-04-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_listing_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buyer',
        ),
    ]
