# Generated by Django 5.1.5 on 2025-04-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_listing_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('not_sold', 'Not Sold'), ('sold', 'Sold'), ('static', 'Static')], default='not_sold', max_length=10),
        ),
    ]
