# Generated by Django 5.1.5 on 2025-04-29 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_friendrequest_options_alter_profile_currency'),
        ('marketplace', '0011_alter_listing_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_listing', to='accounts.profile'),
        ),
    ]
