# Generated by Django 5.2 on 2025-04-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_currency_friendrequest_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
