# Generated by Django 5.1.5 on 2025-04-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.PositiveBigIntegerField(default=1000),
        ),
    ]
