# Generated by Django 5.0 on 2025-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name_plural': 'Friend Requests'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.PositiveBigIntegerField(default=100000),
        ),
    ]
